
import { NextRequest } from 'next/server';
import { getServerSession } from '@/lib/auth';
import {
  globalCodeEmitters,
  pendingCodeChunks,
  connectionTimestamps,
  encoder,
  HEARTBEAT_INTERVAL,
  cleanupConnection,
  flushBufferedChunks
} from '@/lib/scaffolder/code-stream/emitter';

/**
 * SSE endpoint for streaming generated code during app generation
 * GET /api/scaffolder/code-stream/[conversationId]
 * 
 * Streams code chunks as they are generated by the LLM
 */

export async function GET(
  request: NextRequest,
  { params }: { params: { conversationId: string } }
) {
  try {
    const session = await getServerSession();

    if (!session?.user?.id) {
      console.log('📡 Code Stream: Unauthorized request');
      return new Response('Unauthorized', { status: 401 });
    }

    const conversationId = params.conversationId;
    console.log(`📡 Code Stream: Connection request for ${conversationId}`);

    // Create SSE stream
    const stream = new ReadableStream({
      start(controller) {
        // Store controller in global map
        globalCodeEmitters.set(conversationId, controller);
        connectionTimestamps.set(conversationId, Date.now());
        console.log(`📡 Code Stream: Controller registered for ${conversationId}`);
        
        // Send initial connection acknowledgment
        const connectedMsg = {
          id: `connected-${Date.now()}`,
          type: 'connected',
          conversationId,
          timestamp: new Date().toISOString(),
          bufferedCount: pendingCodeChunks.get(conversationId)?.length || 0,
        };
        controller.enqueue(encoder.encode(`data: ${JSON.stringify(connectedMsg)}\n\n`));
        
        // Flush any buffered chunks immediately
        flushBufferedChunks(conversationId);
        
        // Keep connection alive with heartbeat
        const heartbeat = setInterval(() => {
          try {
            if (!globalCodeEmitters.has(conversationId)) {
              clearInterval(heartbeat);
              return;
            }
            controller.enqueue(encoder.encode(`: heartbeat ${Date.now()}\n\n`));
          } catch {
            clearInterval(heartbeat);
            cleanupConnection(conversationId);
          }
        }, HEARTBEAT_INTERVAL);

        // Cleanup on client disconnect
        request.signal.addEventListener('abort', () => {
          console.log(`📡 Code Stream: Client disconnected ${conversationId}`);
          clearInterval(heartbeat);
          cleanupConnection(conversationId);
          try {
            controller.close();
          } catch {
            // Already closed
          }
        });
      },
    });

    return new Response(stream, {
      headers: {
        'Content-Type': 'text/event-stream',
        'Cache-Control': 'no-cache, no-transform',
        'Connection': 'keep-alive',
        'X-Accel-Buffering': 'no',
      },
    });
  } catch (error) {
    console.error('📡 Code Stream: Endpoint error:', error);
    return new Response('Internal Server Error', { status: 500 });
  }
}
